CONFIG_RING_BUFFER=y
CONFIG_POLL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_I2C=y
CONFIG_SENSOR=y

CONFIG_TIMING_FUNCTIONS=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.168.7.2"
CONFIG_NET_CONFIG_MY_IPV4_NETMASK="255.255.255.0"
# CONFIG_NET_CONFIG_NEED_IPV4=y

CONFIG_NET_CONFIG_INIT_TIMEOUT=10
CONFIG_NET_PKT_RX_COUNT=8
CONFIG_NET_PKT_TX_COUNT=8
CONFIG_NET_BUF_RX_COUNT=16
CONFIG_NET_BUF_TX_COUNT=16
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# zephyr bug
CONFIG_NET_TC_TX_COUNT=1

CONFIG_FPU=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_NEWLIB_LIBC_FLOAT_SCANF=y

# use only for debugging, not actual production
CONFIG_ASSERT=y
CONFIG_LOG=y
CONFIG_LOG_PRINTK=n  # needed so there is not a huge delay with printk
