CONFIG_BOOT_BANNER=n

CONFIG_RING_BUFFER=y
CONFIG_POLL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_GPIO=y
CONFIG_PWM=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
CONFIG_CDC_ACM_SERIAL_PID=0x0004
CONFIG_CDC_ACM_SERIAL_PRODUCT_STRING="Maritime"
# USB is output of logs, so turning on logs of USB would be recursive
CONFIG_USB_CDC_ACM_LOG_LEVEL_OFF=y

# use only for debugging, not actual production
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MAX_LEVEL=1
CONFIG_LOG_PRINTK=n  # needed so there is not a huge delay with printk
